pipelines/templates/jobs-deploy-infra.yaml

This was added as we move into europe

location parameterization

---

.gitignore
src/webui/src/components/pages/packages/flyouts/index.js
src/webui/src/components/pages/packages/flyouts/packageNew/index.js
src/webui/src/components/pages/packages/flyouts/packageNew/packageNew.container.js
src/webui/src/components/pages/packages/flyouts/packageNew/packageNew.js
src/webui/src/components/pages/packages/flyouts/packageNew/packageNew.scss
src/webui/src/components/pages/packages/modals/deletePackage/deletePackage.container.js
src/webui/src/components/pages/packages/modals/index.js
src/webui/src/components/pages/packages/packages.container.js
src/webui/src/components/pages/packages/packages.js
src/webui/src/components/pages/packages/packages.scss
src/webui/src/components/pages/packages/packages.test.js
src/webui/src/components/pages/packages/packagesGrid/index.js
src/webui/src/components/pages/packages/packagesGrid/packagesGrid.js
src/webui/src/components/pages/packages/packagesGrid/packagesGrid.scss
src/webui/src/components/pages/packages/packagesGrid/packagesGridConfig.js

I'm adding back the packages page webui code, and removing some lines that didn't seem to be accomplishing anything (except breaking our webui code) from .gitignore

re-adding packages page code which was being ignored

---

src/webui/src/components/pages/deployments/deploymentsHome/flyouts/deploymentNew/deploymentNew.js

Team,
Changes are made to display packagename along with package version in deployment details page.
This pr raised for work item [AB#13733](https://dev.azure.com/3M-Bluebird/AzurePlatform/_workitems/edit/13733).

Bug-13733: Fixed Missing Package Description

---

pipelines/cd/infra.yaml

Team,
Changes are made to add the SysAdmins for all the environments.
This PR is raised for the bug AB#13346

Updated the Sysadmin details

---

src/webui/src/components/pages/packages/flyouts/packageJSON/index.js
src/webui/src/components/pages/packages/flyouts/packageJSON/packageJSON.container.js
src/webui/src/components/pages/packages/flyouts/packageJSON/packageJSON.js
src/webui/src/components/pages/packages/packages.js

Hi Team,
This PR includes the changes of [AB#14100](https://dev.azure.com/3M-Bluebird/AzurePlatform/_workitems/edit/14100).
These code changes are checked in as part of user story [AB#13083](https://dev.azure.com/3M-Bluebird/AzurePlatform/_workitems/edit/13083), however changes were lost in the open source repo.
Added the changes back.

Bug-14100: Added changes to reflect packageJson display changes

---

src/webui/src/services/models/tenantModels.js

https://dev.azure.com/3M-Bluebird/AzurePlatform/_workitems/edit/14278

Remove hardcoded role names

---

pipelines/cd/infra-crsl.yaml

Added the scheduled trigger.
This PR is as part of the User-Story: 14330 [AB14330](https://dev.azure.com/3M-Bluebird/AzurePlatform/_backlogs/backlog/Odin/Stories/?workitem=14330)

User story 14330 schedule trigger

---

pipelines/cd/app-config-template.json
src/services/device-telemetry/WebService/Controllers/MessagesController.cs
test/services/device-telemetry/WebService.Test/Controllers/MessagesControllerTest.cs

Changed Message Retrieval Count Limit

Story 14093: UI Time Frame Selection Not Properly Displaying Long-Term Telemetry

---

pipelines/cd/infra-crsl.yaml
src/webui/src/components/pages/devices/flyouts/deviceJobs/deviceJobMethods.js

We were noticing an under-utilization. I am decreasing the node size to see if we can get by with less powerful nodes

chore(decrease-crsl-prod): Decrease crsl prod environments aks node sizes

---

src/services/device-telemetry/Services/DeviceFileUploads.cs
src/services/device-telemetry/Services/IDeviceFileUploads.cs
src/services/device-telemetry/Services/Models/DeviceUpload.cs
src/services/device-telemetry/Services/Models/DownloadRequest.cs
src/services/device-telemetry/WebService/Controllers/DeviceFilesController.cs
src/services/device-telemetry/WebService/Models/DeviceFileApiModel.cs
src/services/device-telemetry/WebService/Models/DeviceFileListApiModel.cs
src/webui/public/locales/en/translations.json
src/webui/src/components/pages/devices/flyouts/deviceDetails/deviceDetails.js
src/webui/src/components/pages/devices/flyouts/deviceDetails/deviceDetails.scss
src/webui/src/services/models/telemetryModels.js
src/webui/src/services/telemetryService.js
test/services/device-telemetry/WebService.Test/Controllers/DeviceFilesControllerTest.cs

**Description**
- This PR has the changes to display the file uploads by devices in the Device details flyout and provides option to download to analyse the file.
**WorkItem**
- [AB#11545](https://dev.azure.com/3M-Bluebird/AzurePlatform/_workitems/edit/11545)

feat(webui): Access device file uploads in device details flyout

---

src/webui/public/locales/en/translations.json

Added missing translation for device group pin

fix(webui) - added translations for device group pin

---

pipelines/templates/jobs-deploy-infra.yaml

There were some defaults leftover, ran into issue with GDPR deploy

chore(update-pipeline-location-overrides): Override locations in pipelines

---

src/webui/src/components/pages/dashboard/panels/telemetry/advancedPivotMenu.js

**Description:**
This PR has the changes for hiding left and right arrow when we have less attributes.

fix(webui): Updated scroll for the attributes of telemetry 

---

src/webui/src/components/shell/flyouts/manageDeviceGroups/views/deviceGroupForm.js
src/webui/src/components/shell/flyouts/manageDeviceGroups/views/deviceGroups.js
src/webui/src/store/reducers/appReducer.js

Fixed the device group pin save issue.

fix(device-group-pin): Device Group pin save issue

---

src/webui/src/components/shell/flyouts/manageDeviceGroups/manageDeviceGroups.container.js
src/webui/src/services/identityGatewayService.js
src/webui/src/store/reducers/appReducer.js

This changes to select default device group when no active device group found.

fix(webui): Select default device group when no active device group

---

pipelines/ci/test.yaml

Added task in test yaml to publish UI test screenshots to artifacts

feat(test): added task in yaml to publish UI test screenshots to artifacts

---

pipelines/ci/test.yaml

Allowed to continue on error in test yaml

fix(test) : allowed to continue on error in test yaml

---

src/services/iothub-manager/Services/Deployments.cs
src/webui/src/components/pages/deployments/deploymentsHome/deployments.js
src/webui/src/components/pages/deployments/deploymentsHome/deployments.scss
src/webui/src/components/shared/cellRenderers/isActiveDeploymentRenderer/isActiveDeploymentRenderer.js
src/webui/src/components/shared/pcsGrid/pcsGridConfig.js

Hi Team,
This PR includes the changes to update for fetching of deployment metrics when less priority deployments created.

Updated to fetch deployment metrics for less priority deployments

---

pipelines/cd/infra-emd.yaml

Restores original EMD AKS version to prevent upgrade.

fix: restore EMD AKS Version

---

docs/CHANGELOG.md
src/services/iothub-manager/Services/Deployments.cs

Hi Team,
This PR includes the changes of the release version and devicegroupId reference for the migrated deployments

fix: updated release url and devicegroupId reference

---

pipelines/templates/jobs-deploy-infra.yaml

Hi All,
This PR includes the fix for Bug-18500.This issue is regarding populating the App Configuration service.

Updated the EventHub rootKey value

---

pipelines/templates/jobs-deploy-code.yaml
pipelines/templates/variables-all.yaml
src/services/identity-gateway/WebService/Controllers/UserSettingsController.cs
src/webui/src/components/app.js
src/webui/src/components/pages/dashboard/dashboard.js
src/webui/src/components/pages/deployments/deploymentsHome/deployments.js
src/webui/src/components/pages/devices/devices.js
src/webui/src/components/pages/maintenance/maintenance.js
src/webui/src/components/pages/packages/packages.js
src/webui/src/components/pages/rules/rules.js
src/webui/src/components/pages/users/users.js
src/webui/src/services/identityGatewayService.js
src/webui/src/utilities/httpClient.js

Hi Team,
This PR includes the changes to automatically refresh the browser cache after every code deployment.

Changes to Refresh the cache after every successful deployment

---

charts/mmm-iot-service/templates/deployment.yaml
pipelines/ci/test.yaml

Changed AntiMalware@3 to address Bug 19167

fix(pipeline): out-of-date signature for windows defender 

---

pipelines/ci/test.yaml

- Updated configuration for task: AntiMalware@3: Scan for malware
- Updated configuration for task: HelmDeploy@0: Install services Helm chart

Bug fix 19186.

---

pipelines/ci/test.yaml

fix(pipeline): use cluster admin in install services

---

charts/mmm-iot-service/templates/deployment.yaml
pipelines/ci/test.yaml

HelDeploy@0 revert back to command: install

revert back to install

---

src/webui/public/locales/en/translations.json

Change for resolving the translations conflict issue

fix(webui): translation conflict update

---

docs/CHANGELOG.md
src/webui/src/app.config.js

updated changelog
updated app.config

chore: update release notes for 5.3.0

---

src/webui/public/locales/en/translations.json
src/webui/src/components/app.js
src/webui/src/components/pages/devices/deviceTelemetry/deviceTelemetry.container.js
src/webui/src/components/pages/devices/deviceTelemetry/deviceTelemetry.js
src/webui/src/components/pages/devices/devices.js
src/webui/src/components/pages/devices/devicesGrid/devicesGrid.js
src/webui/src/components/pages/devices/devicesRouter.js
src/webui/src/components/pages/index.js
src/webui/src/components/shared/forms/btn.js

Changes include:
1. New page for showing device telemetry for selected devices

feat(webui): device telemetry page

---

src/webui/src/components/pages/devices/devices.js
src/webui/src/components/pages/devices/devices.scss
src/webui/src/components/pages/rules/rules.js
src/webui/src/components/pages/users/users.js
src/webui/src/components/pages/users/users.scss
src/webui/src/components/shared/contextMenu/searchInput/searchInput.scss

Changes for moving the search boxes from toolbar to the page content section, above the grid.
Pages affected:
1. Device explorer
2. User Management
3. Rules

feat(webui): shift searchbox location

---

pipelines/cd/infra-chim.yaml

Updating the location name to centralus as the resources are present in centralus

Updated the location from eastus2 to centralus

---

src/webui/src/components/pages/packages/packagesGrid/packagesGridConfig.js
src/webui/src/utilities/methods.js

Changes to show tooltip for cell data in grid.

feat(webui): Table cell tooltip changes

---

pipelines/cd/infra-crsl.yaml

Updated the K8's version of CRSL QA and Workbench to 1.16.10

Updated the K8's version to 1.16.10

---

src/webui/src/components/pages/devices/devices.js
src/webui/src/components/shared/contextMenu/contextMenu.scss
src/webui/src/components/shared/contextMenu/contextMenuAgile.js
src/webui/src/components/shared/contextMenu/index.js
src/webui/src/components/shared/forms/styles/btn.scss
src/webui/src/components/shell/shell.js

Created a component to overlay crowded buttons in context menu to a dropdown.
Used this component in device explorer page

feat(webui): overlay context menu

---

pipelines/ci/test.yaml

Added changes to wait till revers-proxy pod in test is up

fix(test): wait till reverse-proxy up for test

---

src/webui/public/locales/en/translations.json
src/webui/src/components/pages/deployments/deploymentsHome/deployments.container.js
src/webui/src/components/pages/deployments/deploymentsHome/deployments.js
src/webui/src/components/pages/deployments/deploymentsHome/flyouts/deploymentStatus/deploymentStatus.js
src/webui/src/components/pages/devices/devicesGrid/devicesGrid.container.js
src/webui/src/components/pages/devices/devicesGrid/devicesGrid.js
src/webui/src/components/pages/devices/flyouts/deviceDetails/deviceDetails.js
src/webui/src/components/pages/devices/flyouts/deviceJobs/deviceJobs.js
src/webui/src/components/pages/packages/flyouts/packageJSON/packageJSON.js
src/webui/src/components/pages/packages/packages.js
src/webui/src/components/pages/rules/flyouts/editRuleFlyout.js
src/webui/src/components/pages/rules/flyouts/ruleDetailsFlyout.js
src/webui/src/components/pages/rules/rules.container.js
src/webui/src/components/pages/rules/rules.js
src/webui/src/components/pages/rules/rulesGrid/rulesGrid.js
src/webui/src/components/shared/copyModal/copyModal.js
src/webui/src/components/shared/copyModal/copyModal.scss
src/webui/src/components/shared/flyout/flyout.js
src/webui/src/components/shared/flyout/flyout.scss
src/webui/src/components/shared/pcsGrid/pcsGrid.js
src/webui/src/utilities/methods.js

Changes include Get link functionality for below flyouts:
1. Devices: Details and Jobs 
2. Rules: Details and edit
3. Packages: Package View(Json)
4. Deployments: Status

feat(webui): flyout links

---

pipelines/ci/test.yaml

Integrated whiteSource bolt with test pipeline

feat(pipeline): Integrated whiteSource bolt with test pipeline

---

docs/CHANGELOG.md
src/webui/src/app.config.js

Create new release 5.4.0.  Primarily has CHIM improvements.

chore: update release notes for 5.4.0

---

src/webui/src/components/shell/flyouts/settings/settings.js

Hi Team,
As part of this PR we have included the changes of auto refresh when we open settings flyout

feat(webui): Added auto refresh on settings flyout

---

pipelines/ci/test.yaml

Increasing the timeout value of reverse-proxy pod as part of bug-21940

Updated the test yaml file

---

src/webui/src/components/shared/pcsGrid/pcsGrid.scss

Enabling text highlight for Grid cell data

feat(webui): Enable grid cell text highlight

---

src/services/common/Services/Helpers/QueryBuilder.cs
src/services/device-telemetry/Services/Alarms.cs
src/services/device-telemetry/Services/IAlarms.cs
src/services/device-telemetry/Services/IRules.cs
src/services/device-telemetry/Services/Rules.cs
src/services/device-telemetry/WebService/Controllers/RulesController.cs
src/services/device-telemetry/WebService/Models/RuleApiModel.cs
src/services/device-telemetry/WebService/Models/RuleListApiModel.cs
src/webui/src/services/models/telemetryModels.js
src/webui/src/services/telemetryService.js
src/webui/src/store/reducers/rulesReducer.js

Hi Team,
We have fixed the alarms issue removing the subsequent request to fetch the last trigger date and also querying active rules.

fix(webui & api): Fixed rule and alarms issue

---

pipelines/cd/arm/templates/functions.json

PR includes the changes to access functions only using HTTPS

chore(functions): Included HTTPSOnly property for Sites in template

---

src/services/device-telemetry/Services/Rules.cs
test/services/device-telemetry/Services.Test/RulesTest.cs

Hi Team,
As part of this PR we have fixed the extra effort on cosmos collection for the logging

fix(api): Fixed random error with deletion of rules

---

docs/CHANGELOG.md
src/webui/src/app.config.js

- Fixed performance issues reading "deleted" rules
- Fixed rule deletion to delete rules
- Upgraded versions of several dlls harden security 
- Fixed rule and alarms 502 issue
- Enabled grid cell text highlight
- Addressed auto refresh on settings flyout
- Force support for HTTPS in template

chore: update release notes for 5.4.1

---

src/services/tenant-manager/Services/Models/UserTenantModel.cs
src/services/tenant-manager/Services/TenantContainer.cs
src/webui/src/components/shell/flyouts/profile/profile.scss
src/webui/src/components/shell/flyouts/profile/tenantGrid.js
src/webui/src/services/models/tenantModels.js

Changes for displaying IotHub Name(along with Tenant Name) in Tenants grid of User profile flyout

feat(webui): Display Iothub name in Tenants grid

---

src/webui/public/locales/en/translations.json
src/webui/src/components/pages/devices/devices.container.js
src/webui/src/components/pages/devices/devices.js
src/webui/src/components/pages/devices/devices.scss
src/webui/src/components/shell/deviceGroupDropdown/deviceGroupDropdown.js
src/webui/src/services/iotHubManagerService.js
src/webui/src/services/models/iotHubManagerModels.js
src/webui/src/store/reducers/deploymentsReducer.js
src/webui/src/store/reducers/devicesReducer.js

Changes for:
1. Fetching the devices using Continuation Token when there is one
2. Option to allow or restrict loading all the devices(when there is CToken) in Device Explorer page using a toggle.

feat(webui): Devices Continuation token changes

---

pipelines/templates/jobs-deploy-infra.yaml
pipelines/templates/variables-deploy-infra.yaml
src/services/identity-gateway/Services/Helpers/InviteHelpers.cs

Hi Team,
This PR includes the changes of updating FromEmail and reading it from AppConfiguration

Fix kci sendgrid issue

---

src/services/identity-gateway/WebService/Controllers/UserTenantController.cs
src/services/tenant-manager/Services/External/IIdentityGatewayClient.cs
src/services/tenant-manager/Services/External/IdentityGatewayClient.cs
src/services/tenant-manager/Services/Models/IdentityGatewayApiModel.cs
src/services/tenant-manager/Services/TenantContainer.cs

Hi Team,
This PR includes the changes of adding system admins as users to newly created Tenant

feat(api) : Updated code to add system admins as users to newly created Tenant

---

src/services/iothub-manager/Services/Devices.cs
src/services/iothub-manager/Services/IDevices.cs
src/services/iothub-manager/Services/Models/DeviceConnectionStatusCountModel.cs
src/services/iothub-manager/Services/Models/DeviceStatisticsServiceModel.cs
src/services/iothub-manager/WebService/Controllers/DevicesController.cs
src/services/iothub-manager/WebService/Models/DeviceStatisticsApiModel.cs
src/webui/src/components/pages/dashboard/dashboard.container.js
src/webui/src/components/pages/dashboard/dashboard.js
src/webui/src/components/pages/devices/flyouts/deviceDelete/deviceDelete.container.js
src/webui/src/components/pages/devices/flyouts/deviceDelete/deviceDelete.js
src/webui/src/components/pages/devices/flyouts/deviceNew/deviceNew.container.js
src/webui/src/components/pages/devices/flyouts/deviceNew/deviceNew.js
src/webui/src/components/shell/flyouts/createDeviceQuery/createDeviceQuery.container.js
src/webui/src/components/shell/flyouts/createDeviceQuery/views/createDeviceQueryForm.js
src/webui/src/components/shell/resetActiveDeviceQueryBtn/resetActiveDeviceQueryBtn.container.js
src/webui/src/components/shell/resetActiveDeviceQueryBtn/resetActiveDeviceQueryBtn.js
src/webui/src/services/iotHubManagerService.js
src/webui/src/services/models/iotHubManagerModels.js
src/webui/src/store/reducers/devicesReducer.js

.  Added a service to fetch Total device count and connected device count form IoT hub.
.  Updated to webui to integrate service.

feat(webui) : Changes to fetch device statistics from IoT Hub

---

src/webui/src/components/pages/devices/devices.container.js
src/webui/src/components/pages/devices/devices.js
src/webui/src/components/shell/deviceGroupDropdown/deviceGroupDropdown.container.js
src/webui/src/components/shell/deviceGroupDropdown/deviceGroupDropdown.js
src/webui/src/components/shell/deviceGroupDropdown/deviceGroupDropdown.scss
src/webui/src/store/reducers/devicesReducer.js

Changes to display counts of Devices loaded vs Total Devices in the toolbar

feat(webui): Display device counts in tool bar

---

src/services/identity-gateway/WebService/Controllers/UserSettingsController.cs

- Updated active device group service role for readonly and member users

 fix(service) : fixed readonly user device group issue

---

pipelines/templates/jobs-deploy-infra.yaml

fix deprecated ingress repo with helm stable repo

---

charts/mmm-iot-platform-ingress/requirements.yaml

Updated ingress chart in platform-ingress chart

updated ingress chart in platform-ingress chart

---

src/webui/src/components/pages/rules/flyouts/ruleEditor/ruleEditor.js
src/webui/src/components/pages/rules/flyouts/ruleSummary/ruleSummary.js

Note from Developer(@jnallagatla): Fixed issue with Rule creation.

fix(webui): Rule Creation

---

pipelines/templates/jobs-deploy-infra.yaml

updated script to append sysadmins

Code changes to append the sysadmins to the table.

---

pipelines/templates/jobs-deploy-infra.yaml
pipelines/templates/variables-deploy-infra.yaml
src/services/device-telemetry/WebService/Controllers/AlarmsByRuleController.cs
src/services/device-telemetry/WebService/Controllers/AlarmsController.cs
src/services/device-telemetry/WebService/Controllers/MessagesController.cs
test/services/device-telemetry/WebService.Test/Controllers/AlarmsByRuleControllerTest.cs

feat: Increase device limit

---

src/webui/src/components/shell/flyouts/profile/profile.scss
src/webui/src/components/shell/flyouts/profile/tenantGrid.js

Fixed alignment issue in Tenants grid under User profile

fix(web): Tenant name UI issue

---

src/functions/deployment-sync/Shared/DeploymentSyncService.cs

Hi Team,
This PR has the changes of updated logic while fetching device twins with continuous token when we save twin information.

fix(api): Updated fetching device twin with continous token

---

src/services/iothub-manager/Services/Devices.cs
src/webui/src/components/pages/devices/devices.js
src/webui/src/services/iotHubManagerService.js

- Add a check not to get cached records when ctoken is present

fix(service) - Corrected cToken changes

---

src/webui/src/components/pages/deployments/deploymentsHome/deployments.js
src/webui/src/components/pages/devices/devices.js
src/webui/src/components/pages/devices/devices.scss
src/webui/src/components/pages/maintenance/maintenance.js
src/webui/src/components/pages/maintenance/maintenance.scss
src/webui/src/components/pages/maintenance/summary/summary.js
src/webui/src/components/pages/rules/rules.js
src/webui/src/components/pages/rules/rulesGrid/rulesGrid.js
src/webui/src/components/pages/users/users.js
src/webui/src/components/shared/pageTitle/pageTitle.js
src/webui/src/components/shared/pageTitle/pageTitle.scss
src/webui/src/components/shared/pcsGrid/pcsGrid.js
src/webui/src/components/shared/pcsGrid/pcsGrid.scss

- Changes to have Common Grid Search Input
- Reduced the page title  and font size

feat(webui) - ui enhancements page title font size and common grid search input

---

src/services/iothub-manager/Services/Devices.cs

- Ignored deserialization exception to allow query.

fix(service) - fixed to show device details in deployment details page

---

src/webui/public/locales/en/translations.json
src/webui/src/components/pages/packages/flyouts/packageJSON/packageJSON.js
src/webui/src/components/pages/packages/flyouts/packageJSON/packageJSON.scss
src/webui/src/components/pages/packages/flyouts/packageNew/packageNew.js
src/webui/src/components/pages/packages/packages.js
src/webui/src/components/pages/packages/packagesGrid/packagesGrid.js
src/webui/src/components/pages/packages/packagesGrid/packagesGridConfig.js
src/webui/src/components/shared/cellRenderers/copyToClipBoardRenderer/copyToClipBoardRenderer.js
src/webui/src/components/shell/flyouts/settings/firmwareVariableGrid.js
src/webui/src/services/models/configModels.js

Hi Team,
As part of this PR, we have included the changes for unique Id template variable

feat(UI) : new template variable for uniqueId

---

src/webui/src/components/pages/devices/flyouts/deviceDetails/deviceDetails.js

Hi Team,
As part of this PR, we have added logic to fetch the deployment history details on device change

fix(UI): Device history content update

---

pipelines/templates/jobs-deploy-infra.yaml
src/services/iothub-manager/Services/Deployments.cs
src/webui/public/locales/en/translations.json
src/webui/src/components/pages/devices/flyouts/deviceDetails/deviceDetails.js
src/webui/src/services/models/iotHubManagerModels.js

- Updated device history column name
-  Updated mapping

fix(webui) - updated device history column name

---

docs/CHANGELOG.md
src/webui/src/app.config.js

chore: release 5.4.3

---

pipelines/cd/infra-chim.yaml
pipelines/cd/infra-crsl.yaml

Updated aks version to 1.19.3 in chim-dev, crsl-dev and crsl-qa

update AKS version to 1.19.3 in CHIM DEV, CRSL QA, CRSL Dev env

---

src/services/iothub-manager/Services/Models/DeviceReportServiceModel.cs
src/webui/src/components/pages/devices/advanceSearch/advanceSearch.js
src/webui/src/components/shared/pcsGrid/pcsGrid.js

Fixed few issues in the device search page

fix(webui): Device search page

---

src/webui/public/index.html

Hi Team,
As part of this PR we have added the changes for refreshing the cache

fix(UI) : Added changes for refreshing cache

---

pipelines/cd/infra-chim.yaml

Updated AKS version to 1.19.3 in CHIM QA

Updated AKS version to 1.19.3 in CHIM QA

---

src/functions/deployment-sync/Shared/DeploymentSyncService.cs

Deployment details: Previous firmware save logic update

fix(api): Previous firmware save update

---

pipelines/cd/code.yaml
pipelines/cd/infra-psd.yaml

PSD Test Environment Resource Names
--
Subscription | 3M-ASDT05-PSD-CS-IOT-QA
Resource Group | rg-iot-psd-test
Location | Central US
UI | https://psdiot-aks-test.centralus.cloudapp.azure.com
DPS | psdbb-e2-dps-test-05
IoT Hub | psd-e2-iot-test-01
Cosmos DB | psdiot-cosmos-test
AKS RG | MC-rg-iot-psd-test_psdiot-aks-test_centralus
PSD Test Environment Settings
AKS Version | 1.19.3
Use Blue/Green | TRUE
Az Functions version | 3.x
Deploy Dependency | Dev

Pipeline Updates: New Serenity Instance called Test in PSD QA Env

---

pipelines/cd/infra-chim.yaml
src/webui/src/components/pages/dashboard/dashboard.js
src/webui/src/components/pages/deployments/deploymentsHome/deployments.js
src/webui/src/components/pages/devices/deviceTelemetry/deviceTelemetry.js
src/webui/src/components/pages/devices/devices.js
src/webui/src/components/pages/devices/devicesGrid/devicesGrid.js
src/webui/src/components/pages/maintenance/ruleDetails/ruleDetails.container.js
src/webui/src/components/pages/maintenance/ruleDetails/ruleDetails.js
src/webui/src/components/pages/maintenance/summary/summary.js
src/webui/src/components/pages/packages/packages.js
src/webui/src/components/pages/rules/rules.js
src/webui/src/components/pages/rules/rulesGrid/rulesGrid.js
src/webui/src/components/shell/flyouts/profile/profile.scss
src/webui/src/components/shell/flyouts/profile/tenantGrid.js
src/webui/src/utilities/methods.js

1. Navigation issues
2. Flyout open errors
3. UI alignment errors

fix(webui): Maintenance page issues

---

src/webui/src/components/pages/devices/advanceSearch/advanceSearch.js
src/webui/src/components/pages/devices/devices.container.js
src/webui/src/components/pages/devices/devicesGrid/devicesGrid.container.js
src/webui/src/components/pages/devices/devicesGrid/devicesGrid.js
src/webui/src/store/reducers/devicesReducer.js

Changes for GetLink functionality in Device explorer page after load more

fix(webui): Device explorer Getlink updates after Load more

---

src/services/tenant-manager/Services/Tasks/ARMTemplates/dps.json

Hi Team,
Changes include the fix for DPS and IoTHub Linking.

bug(api): fix for DPS and IoTHub linking

---

src/services/identity-gateway/Services/Models/UserTenantModel.cs
src/services/identity-gateway/Services/UserTenantInput.cs
src/services/identity-gateway/WebService/Controllers/AuthorizeController.cs
src/services/identity-gateway/WebService/Controllers/SystemAdminController.cs
src/services/identity-gateway/WebService/Controllers/UserTenantController.cs
src/services/tenant-manager/Services/External/IIdentityGatewayClient.cs
src/services/tenant-manager/Services/External/IdentityGatewayClient.cs
src/services/tenant-manager/Services/ITenantContainer.cs
src/services/tenant-manager/Services/Models/IdentityGatewayApiModel.cs
src/services/tenant-manager/Services/Models/UserTenantModel.cs
src/services/tenant-manager/Services/TenantContainer.cs
src/services/tenant-manager/WebService/Controllers/TenantController.cs
src/webui/public/locales/en/translations.json
src/webui/src/components/pages/users/usersGrid/usersGrid.js
src/webui/src/components/pages/users/usersGrid/usersGridConfig.js
src/webui/src/services/models/identityGatewayModels.js
test/services/identity-gateway/WebService.Test/Controllers/SystemAdminControllerTest.cs
test/services/identity-gateway/WebService.Test/Controllers/UserTenantControllerTest.cs
test/services/tenant-manager/WebService.Test/Controllers/TenantControllerTest.cs

Hi Team,
PR includes changes for adding Audit Data( CreatedBy and Created Date) for the following flows
- User Addition to Tenant via Invitation
- User Addition to Tenant while creating new Tenant.

feat(webui&api): Audit Data for UserManagement

---

src/webui/src/services/authService.js

Hi Team,
This PR includes code changes that enforce Logout:
- If the token is expired while checking in the getAccessToken Function.
- If the User object is empty while checking in the getAccessToken Function.

feat(webui): Auto LogOff functionality
